-- Kaithi OCR System — Initial DB Setup
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "unaccent";

GRANT ALL PRIVILEGES ON DATABASE kaithi_db TO kaithi;
GRANT ALL ON SCHEMA public TO kaithi;
